// Code generated by hertz generator.

package main

import (
	"go-social-network/data"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	data.Init()
	h := server.Default()

	register(h)
	h.Spin()
}
