// Code generated by hertz generator.

package network

import (
	"go-social-network/biz/handler/middleware"
	"go-social-network/data"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.GetJWTMiddleware(data.Default()).MiddlewareFunc()}
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _poststatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettimelineMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followandunfollowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
